import Head from "next/head";
import Header from "../components/Header";
import Sidebar from "../components/Sidebar";
import CardSwiper from "../components/CardSwiper";
import FooterNav from "../components/FooterNav";
import ProfileInfoModal from "../components/ProfileInfoModal";
import { useRecoilState } from "recoil";
import { profileInfoModalState } from "../atoms/modals";
import { useSession, getSession } from "next-auth/client";

export default function Home() {
  const [open, setOpen] = useRecoilState(profileInfoModalState);
  const [session] = useSession();
  //console.log(session);

  return (
    <div className="bg-gray-100 flex flex-col smlg:flex-row min-h-screen overflow-hidden">
      <Head>
        <title>Unimeet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/**Header */}
      <Header />

      {/**Sidebar for desktop */}
      <Sidebar />

      {/**Cardswiper */}
      <CardSwiper users={[]} />

      {/**Navigation for mobile */}
      <FooterNav />
      <button onClick={() => setOpen(true)}>Open modal</button>
      <ProfileInfoModal />
    </div>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);
  if (!session) {
    return {
      redirect: {
        permanent: false,
        destination: "/auth/signin",
      },
    };
  }

  return {
    props: {
      session,
    },
  };
}
